---
kind: pipeline
name: default-linux-arm64
node:
  drone_lab: true

platform:
  os: linux
  arch: amd64

steps:
  - name: fossa-amd64
    image: rancher/dapper:v0.5.4
    environment:
      FOSSA_API_KEY:
        from_secret: FOSSA_API_KEY
    commands:
      - apk add curl
      - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/spectrometer/master/install.sh | sh"
      - fossa analyze
      - fossa test
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io

---
kind: pipeline
name: default-windows-1809
node:
  drone_lab: true

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
  - name: fossa-windows-1809
    image: rancher/dapper:v0.5.4
    environment:
      FOSSA_API_KEY:
        from_secret: FOSSA_API_KEY
    commands:
      - "Set-ExecutionPolicy Bypass -Scope Process -Force; iex  ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/fossas/spectrometer/master/install.ps1'))"
      - fossa analyze
      - fossa test
    when:
      event:
        - push
      instance:
        - drone-publish.rancher.io